# Generated by Django 5.0.6 on 2024-09-03 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=100)),
                ('batch_faculty', models.CharField(max_length=100)),
                ('batch_startdate', models.DateField()),
                ('batch_starttime', models.TimeField()),
                ('batch_endtime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AddSubject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_image', models.ImageField(blank=True, upload_to='Evenet_Img')),
                ('announcement', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('I', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default=True, max_length=100)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('task_status', models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete')], default='Pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AddStudent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('student_id', models.CharField(max_length=100, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('student_number', models.PositiveIntegerField()),
                ('student_gender', models.CharField(max_length=100)),
                ('student_dob', models.DateField()),
                ('student_address', models.CharField(max_length=300)),
                ('student_image', models.ImageField(blank=True, upload_to='profile_image')),
                ('student_status', models.CharField(max_length=100)),
                ('student_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teacher.addbatch')),
            ],
        ),
        migrations.AddField(
            model_name='addbatch',
            name='batch_subjects',
            field=models.ManyToManyField(to='Teacher.addsubject'),
        ),
        migrations.CreateModel(
            name='Batch_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='batch_files/')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.addbatch')),
            ],
        ),
        migrations.CreateModel(
            name='LeavePlannerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=250)),
                ('leave_type', models.CharField(max_length=100)),
                ('leave_startdate', models.DateField()),
                ('leave_enddate', models.DateField()),
                ('leave_reason', models.CharField(max_length=100)),
                ('leave_status', models.CharField(default='Pending', max_length=100)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.addstudent')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forget_password_tokan', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
